export default [
  {en: 'Hardy', jp: 'がんばりや', 'zh-cn': '努力'},
  {en: 'Lonely', jp: 'さみしがり', 'zh-cn': '孤独'},
  {en: 'Brave', jp: 'ゆうかん', 'zh-cn': '勇敢'},
  {en: 'Adamant', jp: 'いじっぱり', 'zh-cn': '固执'},
  {en: 'Naughty', jp: 'やんちゃ', 'zh-cn': '调皮'},
  {en: 'Bold', jp: 'ずぶとい', 'zh-cn': '大胆'},
  {en: 'Docile', jp: 'すなお', 'zh-cn': '直率'},
  {en: 'Relaxed', jp: 'のんき', 'zh-cn': '悠闲'},
  {en: 'Impish', jp: 'わんぱく', 'zh-cn': '淘气'},
  {en: 'Lax', jp: 'のうてんき', 'zh-cn': '乐天'},
  {en: 'Timid', jp: 'おくびょう', 'zh-cn': '胆小'},
  {en: 'Hasty', jp: 'せっかち', 'zh-cn': '急躁'},
  {en: 'Serious', jp: 'まじめ', 'zh-cn': '认真'},
  {en: 'Jolly', jp: 'ようき', 'zh-cn': '开朗'},
  {en: 'Naive', jp: 'むじゃき', 'zh-cn': '天真'},
  {en: 'Modest', jp: 'ひかえめ', 'zh-cn': '保守'},
  {en: 'Mild', jp: 'おっとり', 'zh-cn': '稳重'},
  {en: 'Quiet', jp: 'れいせい', 'zh-cn': '冷静'},
  {en: 'Bashful', jp: 'てれや', 'zh-cn': '害羞'},
  {en: 'Rash', jp: 'うっかりや', 'zh-cn': '马虎'},
  {en: 'Calm', jp: 'おだやか', 'zh-cn': '沉着'},
  {en: 'Gentle', jp: 'おとなしい', 'zh-cn': '温顺'},
  {en: 'Sassy', jp: 'なまいき', 'zh-cn': '狂妄'},
  {en: 'Careful', jp: 'しんちょう	', 'zh-cn': '慎重'},
  {en: 'Quirky', jp: 'きまぐれ	Q', 'zh-cn': '浮躁'}
]
